apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-akeyless
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}-akeyless
  data:
    - secretKey: db-password
      remoteRef:
        key: /prod/payments/db-password
